export const listData = [
    {
        id: 1,
        status: "Draft",
        quoted_no: "QT-1001",
        opportunity_name: "Aerospace Component Supply",
        quoted_type: "New Quote",
        quoted_priority_display: "High",
        initiated_by_name: "John Smith",
        quoted_due_date: "2026-08-01",
        status_date: "2026-07-20",
        customer_name: "Boeing",
        buyer_name: "Michael Brown",
        program_code: "PRG-001",
        is_nba: true,
        nba_customer_name: "NBA Aerospace",
        opportunity_status: "Open",
        assigned_to_china: false,
    },
    {
        id: 2,
        status: "Submitted",
        quoted_no: "QT-1002",
        opportunity_name: "Automotive Parts Project",
        quoted_type: "Renewal",
        quoted_priority_display: "Medium",
        initiated_by_name: "Sarah Lee",
        quoted_due_date: "2026-08-05",
        status_date: "2026-07-22",
        customer_name: "Tesla",
        buyer_name: "David Wilson",
        program_code: "AUTO-202",
        is_nba: false,
        nba_customer_name: "",
        opportunity_status: "Pending Review",
        assigned_to_china: true,
    },
    {
        id: 3,
        status: "Approved",
        quoted_no: "QT-1003",
        opportunity_name: "Industrial Equipment Contract",
        quoted_type: "Standard",
        quoted_priority_display: "Low",
        initiated_by_name: "Emily Davis",
        quoted_due_date: "2026-08-10",
        status_date: "2026-07-23",
        customer_name: "General Electric",
        buyer_name: "Robert Taylor",
        program_code: "IND-303",
        is_nba: true,
        nba_customer_name: "NBA Industrial",
        opportunity_status: "Won",
        assigned_to_china: false,
    },
    {
        id: 4,
        status: "Rejected",
        quoted_no: "QT-1004",
        opportunity_name: "Medical Device Manufacturing",
        quoted_type: "Custom",
        quoted_priority_display: "High",
        initiated_by_name: "Daniel Kim",
        quoted_due_date: "2026-08-15",
        status_date: "2026-07-24",
        customer_name: "Medtronic",
        buyer_name: "Jessica Clark",
        program_code: "MED-404",
        is_nba: false,
        nba_customer_name: "",
        opportunity_status: "Lost",
        assigned_to_china: true,
    },
    {
        id: 5,
        status: "In Progress",
        quoted_no: "QT-1005",
        opportunity_name: "Electronics Assembly Project",
        quoted_type: "New Quote",
        quoted_priority_display: "Critical",
        initiated_by_name: "Alex Johnson",
        quoted_due_date: "2026-08-20",
        status_date: "2026-07-24",
        customer_name: "Apple",
        buyer_name: "Kevin Anderson",
        program_code: "ELEC-505",
        is_nba: true,
        nba_customer_name: "NBA Electronics",
        opportunity_status: "Negotiation",
        assigned_to_china: false,
    },
];